version: "2"

linters:
  default: none
  enable:
    - err113
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unconvert
    - unused
    - wrapcheck
  exclusions:
    paths:
    - "_test.go"