name: PR-Review

on:
  pull_request:
    branches: [ main ]
env:
  GITHUB_TOKEN: ${{ github.token }}
  LINT_VERSION: "1.25.1"

permissions: 
  contents: read
  packages: write

jobs:
  test:
    outputs:
      VERSION: ${{ steps.go.outputs.version }}
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        check-latest: true
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3


    - name: Generate AWS region file
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws ec2 describe-regions --all-regions --region us-east-1 --query "Regions[].RegionName" --output text >> cmd/aws-regions.txt

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:  
        args: -v
    
    - name: Execute Go tests
      run: make test-coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Test CLI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        go run main.go clean -r us-west-2
        go run main.go version
  
    - name: build & execute
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo "--------------------------------------------------"
        go build -ldflags="-X 'github.com/karl-cardenas-coding/go-lambda-cleanup/cmd.VersionString=0.0.0'" -o=glc -v
        ./glc clean -r us-west-2


    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    -  name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2


    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}


    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        build-args: VERSION=${{steps.dependencies.outputs.VERSION}}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{ github.repository }}:test